inputs:
  reference_elev:
    path_to_elev: "../../../examples/data/Longyearbyen/data/DEM_2009_ref.tif"
    path_to_mask: "../../../examples/data/Longyearbyen/data/glacier_mask/CryoClim_GAO_SJ_1990.shp"
outputs:
  path: "outputs_topo"
statistics:
- median
- nmad
- validcount
terrain_attributes:
- hillshade
- slope
- aspect
- max_curvature
- roughness
- rugosity