inputs:
  reference_elev:
    downsample: 1
    from_vcrs: null
    path_to_elev: ../../../xdem/example_data/Longyearbyen/data/DEM_2009_ref.tif
    path_to_mask: ../../../xdem/example_data/Longyearbyen/data/glacier_mask/CryoClim_GAO_SJ_1990.shp
    to_vcrs: null
outputs:
  level: 1
  path: outputs_topo
statistics:
- median
- nmad
- validcount
terrain_attributes:
- hillshade
- slope
- aspect
- max_curvature
- roughness
- rugosity
